services:
  recipe-advisor-bot-service:
    image: recipe-advisor-bot-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-advisor-bot-service
    volumes:
      - ./env:/app/env
    restart: unless-stopped

  recipe-llm-service:
    image: recipe-llm-service:latest
    container_name: recipe-llm-service
    volumes:
      - ./env:/app/env
    restart: unless-stopped

  recipe-search-service:
    image: recipe-search-service:latest
    container_name: recipe-search-service
    volumes:
      - ./env:/app/env
    restart: unless-stopped

  embedding-service:
    image: semitechnologies/transformers-inference:sentence-transformers-all-mpnet-base-v2-1.9.7
    container_name: embedding-service
    restart: unless-stopped